### ISSUE TITLE
Is is still working ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [reneluria/kdrive-upload#1]
I'm wondering if it's still working ?

```
jeo@PC-JEOFFREY:~$ kdrive-upload /e export.sql.gz
Traceback (most recent call last):
  File "/usr/local/bin/kdrive-upload", line 11, in <module>
    load_entry_point('kdrive-upload===x.x.x', 'console_scripts', 'kdrive-upload')()
  File "/usr/local/lib/python3.8/dist-packages/kdrive_upload-x.x.x-py3.8.egg/kdrive_upload/__main__.py", line 25, in main
  File "/usr/local/lib/python3.8/dist-packages/kdrive_upload-x.x.x-py3.8.egg/kdrive_upload/kdrive.py", line 55, in upload
  File "/usr/local/lib/python3.8/dist-packages/webdavclient3-3.14.6-py3.8.egg/webdav3/client.py", line 663, in upload_sync
  File "/usr/local/lib/python3.8/dist-packages/webdavclient3-3.14.6-py3.8.egg/webdav3/client.py", line 562, in upload
  File "/usr/local/lib/python3.8/dist-packages/webdavclient3-3.14.6-py3.8.egg/webdav3/client.py", line 67, in _wrapper
  File "/usr/local/lib/python3.8/dist-packages/webdavclient3-3.14.6-py3.8.egg/webdav3/client.py", line 646, in upload_file
  File "/usr/local/lib/python3.8/dist-packages/webdavclient3-3.14.6-py3.8.egg/webdav3/client.py", line 230, in execute_request
webdav3.exceptions.ResponseErrorCode: Request to https://connect.drive.infomaniak.com/mydrive/e/export.sql.gz failed with code 403 and message: b''
```

**Comment by reneluria** [comment]
Ok, I see, 
the option `--drive` has a default value of `mydrive` which is the name of my own, use this option to specify the name of the drive you want to upload to
